import type { BoardMechanic, CardDefinition, CardInstance, CardKind, ClueKind } from "./types";

function pairedCellDotCards(
  id: string,
  name: string,
  summary: string,
  interpretation: string,
  ruleKey: string,
): CardDefinition[] {
  return (["white", "black"] as const).map((color) => ({
    id: `${id}-${color}`,
    name: `${name}·${color === "white" ? "白点" : "黑点"}`,
    kind: "clue",
    score: null,
    summary,
    supportedMechanics: ["shade"],
    clue: {
      kind: color === "white" ? "white-dot" : "black-dot",
      min: 0,
      max: 0,
      interpretations: { shade: interpretation },
      ruleKeys: { shade: ruleKey },
    },
  }));
}

function pairedAnchoredDotCards(
  anchor: "edge" | "vertex",
  id: string,
  name: string,
  summary: string,
  interpretation: string,
  ruleKey: string,
): CardDefinition[] {
  return (["white", "black"] as const).map((color) => ({
    id: `${id}-${color}`,
    name: `${name}·${color === "white" ? "白点" : "黑点"}`,
    kind: "clue",
    score: null,
    summary,
    supportedMechanics: ["shade"],
    clue: {
      kind: `${anchor}-${color}-dot` as "edge-white-dot" | "edge-black-dot" | "vertex-white-dot" | "vertex-black-dot",
      min: 0,
      max: 0,
      interpretations: { shade: interpretation },
      ruleKeys: { shade: ruleKey },
    },
  }));
}

function pairedLoopDotCards(
  anchor: "cell" | "edge",
  id: string,
  name: string,
  summary: string,
  interpretation: string,
  ruleKey: string,
): CardDefinition[] {
  return (["white", "black"] as const).map((color) => ({
    id: `${id}-${color}`,
    name: `${name}·${color === "white" ? "白点" : "黑点"}`,
    kind: "clue",
    score: null,
    summary,
    supportedMechanics: ["loop"],
    clue: {
      kind: anchor === "cell"
        ? (color === "white" ? "white-dot" : "black-dot")
        : (color === "white" ? "edge-white-dot" : "edge-black-dot"),
      min: 0,
      max: 0,
      interpretations: { loop: interpretation },
      ruleKeys: { loop: ruleKey },
    },
  }));
}

function numberClueCard(
  id: string,
  name: string,
  kind: ClueKind,
  summary: string,
  ruleKey: string,
  min = 0,
  max = 40,
): CardDefinition {
  return {
    id,
    name,
    kind: "clue",
    score: null,
    summary,
    supportedMechanics: ["number"],
    clue: { kind, min, max, interpretations: { number: summary }, ruleKeys: { number: ruleKey } },
  };
}

function pairedNumberDotCards(
  anchor: "cell" | "edge" | "vertex",
  id: string,
  name: string,
  summary: string,
  ruleKey: string,
): CardDefinition[] {
  return (["white", "black"] as const).map((color) => numberClueCard(
    `${id}-${color}`,
    `${name}·${color === "white" ? "白点" : "黑点"}`,
    anchor === "cell" ? (color === "white" ? "white-dot" : "black-dot") : `${anchor}-${color}-dot`,
    summary,
    ruleKey,
    0,
    0,
  ));
}

const NUMBER_CARD_DEFINITIONS: CardDefinition[] = [
  { id: "rule-number-latin-full", name: "满格 1–N", kind: "global", score: null, summary: "所有有效格填入 1–N；每行每列数字不重复。", supportedMechanics: ["number"], establishesMechanic: "number", ruleKey: "number.latin-1-to-n-full" },
  { id: "rule-number-latin-minus-one", name: "1–N−1 完整行列", kind: "global", score: null, summary: "允许留空；每行每列不重复，并都出现 1–N−1。", supportedMechanics: ["number"], establishesMechanic: "number", ruleKey: "number.latin-1-to-n-minus-one" },
  { id: "rule-number-latin-minus-two", name: "1–N−2 完整行列", kind: "global", score: null, summary: "允许留空；每行每列不重复，并都出现 1–N−2。", supportedMechanics: ["number"], establishesMechanic: "number", ruleKey: "number.latin-1-to-n-minus-two" },
  { id: "rule-number-connected", name: "数字格连通", kind: "global", score: null, summary: "所有数字格正交连通，正交相邻格不能填相同数字。", supportedMechanics: ["number"], establishesMechanic: "number", ruleKey: "number.digit-cells-connected-no-equal-adjacency" },
  numberClueCard("clue-number-edge-sum", "边线数字·和", "edge-number", "数字等于两侧非空数字之和；仅一格有数时等于该数，两格都空不成立。", "number.edge-number.sum"),
  numberClueCard("clue-number-edge-difference", "边线数字·差", "edge-number", "数字等于两侧非空数字的绝对差；仅一格有数时等于该数。", "number.edge-number.difference"),
  numberClueCard("clue-number-edge-product", "边线数字·积", "edge-number", "数字等于两侧非空数字之积；仅一格有数时等于该数。", "number.edge-number.product"),
  numberClueCard("clue-number-edge-contains", "边线数字·包含", "edge-number", "两侧至少一格必须填有该数字。", "number.edge-number.contains"),
  numberClueCard("clue-number-edge-arithmetic", "边线数字·四则", "edge-number", "两侧非空数字经加、减、乘或整除可得到线索；仅一格有数时等于该数。", "number.edge-number.arithmetic"),
  numberClueCard("clue-number-vertex-sum", "格点数字·和", "vertex-number", "数字等于周围非空数字之和，且至少有一个数字。", "number.vertex-number.sum"),
  numberClueCard("clue-number-vertex-contains", "格点数字·包含", "vertex-number", "周围四格至少一格必须填有该数字。", "number.vertex-number.contains"),
  numberClueCard("clue-number-vertex-diagonal-sums", "格点数字·对角和", "vertex-number", "两条对角线各自至少有一个数字，且各自的数字和都等于线索。", "number.vertex-number.diagonal-sums"),
  numberClueCard("clue-number-vertex-diagonal-differences", "格点数字·对角差", "vertex-number", "两条对角线各自至少有一个数字，且各自的绝对差都等于线索。", "number.vertex-number.diagonal-differences"),
  numberClueCard("clue-number-vertex-diagonal-arithmetic", "格点数字·对角四则", "vertex-number", "两条对角线各自至少有一个数字，且各自经四则运算都可得到线索。", "number.vertex-number.diagonal-arithmetic"),
  numberClueCard("clue-number-cell-dot-empty-black", "格内黑点·留空", "black-dot", "黑点格不能填写数字。", "number.cell-dot.empty", 0, 0),
  numberClueCard("clue-number-cell-dot-filled-white", "格内白点·填数", "white-dot", "白点格必须填写数字。", "number.cell-dot.filled", 0, 0),
  numberClueCard("clue-number-cell-dot-odd-white", "格内白点·奇数", "white-dot", "白点格必须填写奇数。", "number.cell-dot.odd", 0, 0),
  numberClueCard("clue-number-cell-dot-even-black", "格内黑点·偶数", "black-dot", "黑点格必须填写偶数。", "number.cell-dot.even", 0, 0),
  ...pairedNumberDotCards("cell", "clue-number-cell-dot-same-color-equal", "格内点·同色同数", "所有同色格内点所在格必须填写同一个数字。", "number.cell-dot.same-color-equal"),
  numberClueCard("clue-number-cell-dot-greater-black", "格内黑点·局部最大", "black-dot", "黑点格数字必须大于所有正交相邻的非空数字。", "number.cell-dot.greater-than-neighbors", 0, 0),
  numberClueCard("clue-number-cell-dot-less-white", "格内白点·局部最小", "white-dot", "白点格数字必须小于所有正交相邻的非空数字。", "number.cell-dot.less-than-neighbors", 0, 0),
  numberClueCard("clue-number-edge-dot-both-filled-black", "边上黑点·两侧有数", "edge-black-dot", "点两侧都必须填写数字。", "number.edge-dot.both-filled", 0, 0),
  ...pairedNumberDotCards("edge", "clue-number-edge-dot-one-filled", "边上点·恰一有数", "点两侧恰好一格填写数字。", "number.edge-dot.exactly-one-filled"),
  numberClueCard("clue-number-edge-dot-both-empty-white", "边上白点·两侧留空", "edge-white-dot", "点两侧都不能填写数字。", "number.edge-dot.both-empty", 0, 0),
  numberClueCard("clue-number-edge-dot-difference-one-white", "边上白点·差一", "edge-white-dot", "点两侧都填数，且数字绝对差为 1。", "number.edge-dot.difference-one", 0, 0),
  numberClueCard("clue-number-edge-dot-ratio-two-black", "边上黑点·二倍", "edge-black-dot", "点两侧都填数，且一个数字是另一个的两倍。", "number.edge-dot.ratio-two", 0, 0),
  numberClueCard("clue-number-edge-dot-sum-five-white", "边上白点·和五", "edge-white-dot", "点两侧数字之和为 5。", "number.edge-dot.sum-five", 0, 0),
  numberClueCard("clue-number-edge-dot-sum-ten-black", "边上黑点·和十", "edge-black-dot", "点两侧数字之和为 10。", "number.edge-dot.sum-ten", 0, 0),
  ...pairedNumberDotCards("edge", "clue-number-edge-dot-same-color-sums", "边上点·同色等和", "所有同色边上点两侧的数字和相同。", "number.edge-dot.same-color-equal-sums"),
  numberClueCard("clue-number-vertex-dot-more-even-black", "格点黑点·偶数多", "vertex-black-dot", "周围四格中偶数格多于奇数格。", "number.vertex-dot.more-even", 0, 0),
  numberClueCard("clue-number-vertex-dot-more-odd-white", "格点白点·奇数多", "vertex-white-dot", "周围四格中奇数格多于偶数格。", "number.vertex-dot.more-odd", 0, 0),
  numberClueCard("clue-number-vertex-dot-more-empty-white", "格点白点·空格多", "vertex-white-dot", "周围四格中留空格多于数字格。", "number.vertex-dot.more-empty", 0, 0),
  numberClueCard("clue-number-vertex-dot-more-filled-black", "格点黑点·数字格多", "vertex-black-dot", "周围四格中数字格多于留空格。", "number.vertex-dot.more-filled", 0, 0),
  numberClueCard("clue-number-vertex-dot-clockwise-white", "格点白点·顺时针递增", "vertex-white-dot", "周围四数从某处起顺时针严格递增。", "number.vertex-dot.clockwise-increasing", 0, 0),
  numberClueCard("clue-number-vertex-dot-counterclockwise-black", "格点黑点·逆时针递增", "vertex-black-dot", "周围四数从某处起逆时针严格递增。", "number.vertex-dot.counterclockwise-increasing", 0, 0),
  numberClueCard("clue-number-vertex-dot-one-consecutive-white", "格点白点·恰一连续对", "vertex-white-dot", "周围四数中恰好一对数字绝对差为 1。", "number.vertex-dot.exactly-one-consecutive-pair", 0, 0),
  numberClueCard("clue-number-vertex-dot-two-consecutive-black", "格点黑点·至少两连续对", "vertex-black-dot", "周围四数中至少两对数字绝对差为 1。", "number.vertex-dot.at-least-two-consecutive-pairs", 0, 0),
  numberClueCard("clue-number-exterior-first", "外提示·首数", "exterior-number", "沿提示方向跳过留空格观察，遇到的第一个数字等于线索。", "number.exterior-number.first-number"),
  numberClueCard("clue-number-exterior-skyscraper-count", "外提示·摩天楼数", "exterior-number", "沿提示方向观察，数字等于可见的递增纪录数字数量。", "number.exterior-number.skyscraper-count"),
  numberClueCard("clue-number-exterior-skyscraper-sum", "外提示·摩天楼和", "exterior-number", "沿提示方向观察，数字等于所有可见递增纪录数字之和。", "number.exterior-number.skyscraper-sum"),
  numberClueCard("clue-number-exterior-first-two", "外提示·前二包含", "exterior-number", "线索数字必须出现在该方向最前两个有效格之一。", "number.exterior-number.first-two-contain"),
];

function regionClueCard(id: string, name: string, kind: ClueKind, summary: string, ruleKey: string, min = 0, max = 40): CardDefinition {
  return { id, name, kind: "clue", score: null, summary, supportedMechanics: ["region"], clue: { kind, min, max, interpretations: { region: summary }, ruleKeys: { region: ruleKey } } };
}

function pairedRegionDotCards(anchor: "cell" | "edge", id: string, name: string, summary: string, ruleKey: string): CardDefinition[] {
  return (["white", "black"] as const).map((color) => regionClueCard(
    `${id}-${color}`,
    `${name}·${color === "white" ? "白点" : "黑点"}`,
    anchor === "cell" ? (color === "white" ? "white-dot" : "black-dot") : `${anchor}-${color}-dot`,
    summary,
    ruleKey,
    0,
    0,
  ));
}

const REGION_CARD_DEFINITIONS: CardDefinition[] = [
  { id: "rule-region-rectangles", name: "矩形分区", kind: "global", score: null, summary: "每个区域都是无缺口矩形。", supportedMechanics: ["region"], establishesMechanic: "region", ruleKey: "region.rectangles" },
  { id: "rule-region-center-symmetric", name: "中心对称分区", kind: "global", score: null, summary: "每个区域都是中心对称图形。", supportedMechanics: ["region"], establishesMechanic: "region", ruleKey: "region.center-symmetric" },
  { id: "rule-region-one-cell-clue", name: "一区一线索", kind: "global", score: null, summary: "每个区域恰好包含一个格内线索；边界线索不计。", supportedMechanics: ["region"], establishesMechanic: "region", ruleKey: "region.exactly-one-cell-clue" },
  { id: "rule-region-all-shapes-distinct", name: "区域形状互异", kind: "global", score: null, summary: "任意两区域经平移、旋转或翻转后都不能全等。", supportedMechanics: ["region"], establishesMechanic: "region", ruleKey: "region.all-shapes-distinct" },
  regionClueCard("clue-region-cell-area", "格内数字·区域面积", "cell-number", "数字等于所在区域的格数。", "region.cell-number.area"),
  regionClueCard("clue-region-cell-boundary-count", "格内数字·邻边数", "cell-number", "数字等于该格四条边中属于区域边界的数量。", "region.cell-number.adjacent-boundary-count", 0, 4),
  regionClueCard("clue-region-cell-neighbor-count", "格内数字·邻区数", "cell-number", "数字等于与所在区域共享边界的不同区域数量。", "region.cell-number.neighboring-region-count"),
  regionClueCard("clue-region-cell-perimeter", "格内数字·区域周长", "cell-number", "数字等于所在区域的单位边周长。", "region.cell-number.perimeter"),
  regionClueCard("clue-region-edge-area-sum", "边线数字·面积和", "edge-number", "边线必须分隔两个区域，数字等于两区域面积之和。", "region.edge-number.area-sum"),
  regionClueCard("clue-region-edge-area-difference", "边线数字·面积差", "edge-number", "边线必须分隔两个区域，数字等于两区域面积绝对差。", "region.edge-number.area-difference"),
  regionClueCard("clue-region-edge-boundary-length", "边线数字·分割线长", "edge-number", "边线必须分隔两个区域，数字等于包含该边的同向连续分割线长度。", "region.edge-number.boundary-length"),
  regionClueCard("clue-region-vertex-region-count", "格点数字·区域数", "vertex-number", "数字等于格点周围四格所属的不同区域数量。", "region.vertex-number.distinct-region-count", 1, 4),
  regionClueCard("clue-region-vertex-area-sum", "格点数字·区域面积和", "vertex-number", "数字等于格点周围涉及的不同区域面积之和，每个区域只计一次。", "region.vertex-number.region-area-sum"),
  regionClueCard("clue-region-vertex-shape-count", "格点数字·形状数", "vertex-number", "数字等于格点周围涉及区域中互不全等的形状数量。", "region.vertex-number.distinct-shape-count", 1, 4),
  ...pairedRegionDotCards("cell", "clue-region-cell-dot-neighborhood", "格内点·四邻同区", "点所在格及其正交邻格必须同属一个区域。", "region.cell-dot.orthogonal-neighborhood-same-region"),
  ...pairedRegionDotCards("cell", "clue-region-cell-dot-center", "格内点·中心对称", "点所在区域必须以该格中心为对称中心。", "region.cell-dot.center-symmetric-about-point"),
  ...pairedRegionDotCards("cell", "clue-region-cell-dot-axis", "格内点·轴对称", "点所在区域必须关于穿过格中心的水平、竖直或对角轴对称。", "region.cell-dot.axis-symmetric-through-point"),
  ...pairedRegionDotCards("cell", "clue-region-cell-dot-rotated-shape", "格内点·同色旋转全等", "所有同色点所在区域允许旋转和平移后全等，不允许翻转。", "region.cell-dot.same-color-rotationally-congruent"),
  ...pairedRegionDotCards("cell", "clue-region-cell-dot-translated-shape", "格内点·同色平移全等", "所有同色点所在区域仅经平移后全等。", "region.cell-dot.same-color-translation-congruent"),
  ...pairedRegionDotCards("edge", "clue-region-edge-dot-boundary", "边上点·分区边界", "点所在边线必须分隔两个区域。", "region.edge-dot.boundary"),
  ...pairedRegionDotCards("edge", "clue-region-edge-dot-congruent", "边上点·两区旋转全等", "点所在边线分隔的两个区域允许旋转和平移后全等，不允许翻转。", "region.edge-dot.rotationally-congruent-regions"),
  ...pairedRegionDotCards("edge", "clue-region-edge-dot-mirror", "边上点·两区镜像", "点所在边线分隔的两个区域必须关于该边线互为镜像。", "region.edge-dot.mirrored-regions"),
  ...pairedRegionDotCards("edge", "clue-region-edge-dot-center", "边上点·区域中心对称", "边线两侧同属一个区域，且区域以点为对称中心。", "region.edge-dot.center-symmetric-about-point"),
  ...pairedRegionDotCards("edge", "clue-region-edge-dot-axis", "边上点·区域轴对称", "边线两侧同属一个区域，且区域关于穿过点的网格轴对称。", "region.edge-dot.axis-symmetric-through-point"),
  regionClueCard("clue-region-vertex-dot-three-lines-white", "格点白点·三线", "vertex-white-dot", "格点发出的四条单位边中恰有三条分区线。", "region.vertex-dot.three-lines", 0, 0),
  regionClueCard("clue-region-vertex-dot-four-lines-black", "格点黑点·四线", "vertex-black-dot", "格点发出的四条单位边全是分区线。", "region.vertex-dot.four-lines", 0, 0),
  ...(["white", "black"] as const).map((color) => regionClueCard(`clue-region-vertex-dot-zero-lines-${color}`, `格点${color === "white" ? "白点" : "黑点"}·零线`, `vertex-${color}-dot`, "格点发出的四条单位边都不是分区线。", "region.vertex-dot.zero-lines", 0, 0)),
  ...(["white", "black"] as const).map((color) => regionClueCard(`clue-region-vertex-dot-center-${color}`, `格点${color === "white" ? "白点" : "黑点"}·中心对称`, `vertex-${color}-dot`, "格点周围同属一个区域，且区域以该格点为对称中心。", "region.vertex-dot.center-symmetric-about-point", 0, 0)),
  ...(["white", "black"] as const).map((color) => regionClueCard(`clue-region-vertex-dot-axis-${color}`, `格点${color === "white" ? "白点" : "黑点"}·轴对称`, `vertex-${color}-dot`, "格点周围同属一个区域，且区域关于穿过该格点的网格轴对称。", "region.vertex-dot.axis-symmetric-through-point", 0, 0)),
  regionClueCard("clue-region-exterior-count", "外提示·区域数", "exterior-number", "数字等于整行或整列涉及的不同区域数量。", "region.exterior-number.distinct-region-count"),
  regionClueCard("clue-region-exterior-longest-run", "外提示·最长同区段", "exterior-number", "数字等于整行或整列中最长连续同区格段长度；删除格切断段。", "region.exterior-number.longest-run"),
  regionClueCard("clue-region-exterior-shortest-run", "外提示·最短同区段", "exterior-number", "数字等于整行或整列中最短连续同区格段长度；删除格切断段。", "region.exterior-number.shortest-run"),
  regionClueCard("clue-region-given-edge", "给定分区边", "given-edge", "该内部边线必须是分区边界。", "region.given-edge.boundary", 0, 0),
];

export const STARTER_GLOBAL_ID = "rule-koburin-open-cells-separate";
export const STARTER_CLUE_ID = "clue-cell-number";

export const CARD_DEFINITIONS: CardDefinition[] = [
  {
    id: STARTER_GLOBAL_ID,
    name: "疏离空格",
    kind: "global",
    score: null,
    summary: "未被回路经过的正交相邻格不能相邻。",
    supportedMechanics: ["loop"],
    establishesMechanic: "loop",
    ruleKey: "loop.unvisited-not-adjacent",
  },
  {
    id: "rule-single-loop",
    name: "单一回路",
    kind: "global",
    score: null,
    summary: "建立回路盘面；答案必须构成一条单一回路。",
    supportedMechanics: ["loop"],
    establishesMechanic: "loop",
    ruleKey: "loop.single-cycle",
  },
  {
    id: "rule-loop-visit-all-unclued",
    name: "遍历无提示格",
    kind: "global",
    score: null,
    summary: "回路必须经过所有没有格内线索的格子。",
    supportedMechanics: ["loop"],
    establishesMechanic: "loop",
    ruleKey: "loop.visit-all-unclued-cells",
  },
  {
    id: "rule-shade-connected",
    name: "黑格相连",
    kind: "global",
    score: null,
    summary: "建立涂黑盘面；所有黑格连成一片。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.connected",
  },
  {
    id: "rule-shade-white-connected",
    name: "白格相连",
    kind: "global",
    score: null,
    summary: "所有留白格正交连成一片。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.white-connected",
  },
  {
    id: "rule-shade-no-black-2x2",
    name: "禁黑方块",
    kind: "global",
    score: null,
    summary: "任意完整的 2×2 区域不能全部涂黑。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.no-black-2x2",
  },
  {
    id: "rule-shade-no-white-2x2",
    name: "禁白方块",
    kind: "global",
    score: null,
    summary: "任意完整的 2×2 区域不能全部留白。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.no-white-2x2",
  },
  {
    id: "rule-shade-no-three",
    name: "黑白不过三",
    kind: "global",
    score: null,
    summary: "一行或一列中不能连续出现三个同色格。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.no-monochrome-run-3",
  },
  {
    id: "rule-shade-no-four",
    name: "黑白不过四",
    kind: "global",
    score: null,
    summary: "一行或一列中不能连续出现四个同色格。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.no-monochrome-run-4",
  },
  {
    id: "rule-shade-equal-lines",
    name: "行列等量",
    kind: "global",
    score: null,
    summary: "每一行与每一列的涂黑格数量都相同。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.equal-row-column-counts",
  },
  {
    id: "rule-shade-black-no-touch",
    name: "黑格不接触",
    kind: "global",
    score: null,
    summary: "任意两个涂黑格不能正交或对角接触。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.black-cells-do-not-touch",
  },
  {
    id: "rule-shade-snake",
    name: "墨蛇",
    kind: "global",
    score: null,
    summary: "至少两个黑格组成一条不分叉、不成环且不接触自身的蛇。",
    supportedMechanics: ["shade"],
    establishesMechanic: "shade",
    ruleKey: "shade.single-snake",
  },
  {
    id: "rule-regions-connected",
    name: "连续分区",
    kind: "global",
    score: null,
    summary: "建立分区盘面；每个区域必须正交连通。",
    supportedMechanics: ["region"],
    establishesMechanic: "region",
    ruleKey: "region.connected",
  },
  ...NUMBER_CARD_DEFINITIONS,
  ...REGION_CARD_DEFINITIONS,
  {
    id: STARTER_CLUE_ID,
    name: "格内数字",
    kind: "clue",
    score: null,
    summary: "解释取决于盘面的主要玩法。",
    supportedMechanics: ["loop", "shade", "number", "region"],
    clue: {
      kind: "cell-number",
      min: 0,
      max: 8,
      interpretations: {
        loop: "上下左右未被回路经过的格数。",
        shade: "周围九格中涂黑格的数量。",
        number: "这个格子必须填入所示数字。",
        region: "该格所在区域的格数。",
      },
      ruleKeys: {
        loop: "loop.cell-number.orthogonal-unvisited",
        shade: "shade.cell-number.neighborhood-nine",
        number: "number.cell-number.fixed",
      },
    },
  },
  {
    id: "clue-loop-cell-number-eight-visited",
    name: "格内数字·八邻经过",
    kind: "clue",
    score: null,
    summary: "数字格不走回路，数字等于周围八格中回路经过的格数。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "cell-number", min: 0, max: 8,
      interpretations: { loop: "自身不被回路经过；数字等于周围八格中被回路经过的格数。" },
      ruleKeys: { loop: "loop.cell-number.eight-visited" },
    },
  },
  {
    id: "clue-loop-cell-number-eight-unvisited",
    name: "格内数字·八邻未经过",
    kind: "clue",
    score: null,
    summary: "数字格不走回路，数字等于周围八格中未被经过的格数。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "cell-number", min: 0, max: 8,
      interpretations: { loop: "自身不被回路经过；数字等于周围八格中未被回路经过的格数。" },
      ruleKeys: { loop: "loop.cell-number.eight-unvisited" },
    },
  },
  {
    id: "clue-loop-cell-number-eight-turns",
    name: "格内数字·八邻转弯",
    kind: "clue", score: null,
    summary: "数字格不走回路，数字等于周围八格中的回路转弯格数。",
    supportedMechanics: ["loop"],
    clue: { kind: "cell-number", min: 0, max: 8, interpretations: { loop: "自身不被回路经过；数字等于周围八格中回路转弯的格数。" }, ruleKeys: { loop: "loop.cell-number.eight-turns" } },
  },
  {
    id: "clue-loop-cell-number-four-visited",
    name: "格内数字·四邻经过",
    kind: "clue",
    score: null,
    summary: "数字格不走回路，数字等于正交四邻中回路经过的格数。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "cell-number", min: 0, max: 4,
      interpretations: { loop: "自身不被回路经过；数字等于正交四邻中被回路经过的格数。" },
      ruleKeys: { loop: "loop.cell-number.four-visited" },
    },
  },
  {
    id: "clue-loop-cell-number-four-turns",
    name: "格内数字·四邻转弯",
    kind: "clue", score: null,
    summary: "数字格不走回路，数字等于正交四邻中的回路转弯格数。",
    supportedMechanics: ["loop"],
    clue: { kind: "cell-number", min: 0, max: 4, interpretations: { loop: "自身不被回路经过；数字等于正交四邻中回路转弯的格数。" }, ruleKeys: { loop: "loop.cell-number.four-turns" } },
  },
  {
    id: "clue-loop-cell-number-inside-vertices",
    name: "格内数字·内部格点",
    kind: "clue", score: null,
    summary: "数字等于该格四个顶点中位于回路内部的数量。",
    supportedMechanics: ["loop"],
    clue: { kind: "cell-number", min: 0, max: 4, interpretations: { loop: "数字等于该格四个顶点中位于回路内部的格点数量。" }, ruleKeys: { loop: "loop.cell-number.inside-vertex-count" } },
  },
  {
    id: "clue-loop-cell-number-grandstands",
    name: "格内数字·看台",
    kind: "clue", score: null,
    summary: "数字格不走回路，数字等于四个邻格背离线索延伸的直线回路段长度之和。",
    supportedMechanics: ["loop"],
    clue: { kind: "cell-number", min: 0, max: 40, interpretations: { loop: "数字格不被回路经过；从其正交邻格开始、沿背离数字格的方向延伸，数字等于这些直线回路段的边长总和。" }, ruleKeys: { loop: "loop.cell-number.outward-segment-length-sum" } },
  },
  {
    id: "clue-loop-cell-number-balance-arms",
    name: "格内数字·两臂之和",
    kind: "clue", score: null,
    summary: "回路必须经过数字格，数字等于从格中心到两侧下一处转弯的长度之和。",
    supportedMechanics: ["loop"],
    clue: { kind: "cell-number", min: 2, max: 40, interpretations: { loop: "回路必须经过数字格；数字等于沿回路两个方向从该格中心到下一处转弯的边长之和。" }, ruleKeys: { loop: "loop.cell-number.arm-length-sum" } },
  },
  {
    id: "clue-loop-edge-number-segment-length",
    name: "边线数字·线段长度",
    kind: "clue", score: null,
    summary: "回路必须穿过该边，数字等于包含该边的整段直线回路长度。",
    supportedMechanics: ["loop"],
    clue: { kind: "edge-number", min: 1, max: 20, interpretations: { loop: "回路必须使用该内部边线；数字等于包含这条边、两端止于转弯格中心的最大直线回路段长度。" }, ruleKeys: { loop: "loop.edge-number.segment-length" } },
  },
  {
    id: "clue-loop-edge-number-outward-length-sum",
    name: "边线数字·向外段长和",
    kind: "clue", score: null,
    summary: "回路不穿过该边，数字等于两侧格背离边线延伸的直线回路段长度之和。",
    supportedMechanics: ["loop"],
    clue: { kind: "edge-number", min: 0, max: 40, interpretations: { loop: "回路不能使用该内部边线；数字等于边线两侧格分别沿背离边线方向延伸的直线回路段边长之和。" }, ruleKeys: { loop: "loop.edge-number.outward-segment-length-sum" } },
  },
  {
    id: "clue-loop-edge-number-visited-cells",
    name: "边线数字·经过格数",
    kind: "clue",
    score: null,
    summary: "数字等于边线两侧被回路经过的格数。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "edge-number", min: 0, max: 2,
      interpretations: { loop: "数字等于内部边线两侧两个格子中被回路经过的格数。" },
      ruleKeys: { loop: "loop.edge-number.visited-cell-count" },
    },
  },
  {
    id: "clue-loop-vertex-number-visited-cells",
    name: "格点数字·经过格数",
    kind: "clue",
    score: null,
    summary: "数字等于格点周围四格中回路经过的格数。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "vertex-number", min: 0, max: 4,
      interpretations: { loop: "数字等于内部格点周围四格中被回路经过的格数。" },
      ruleKeys: { loop: "loop.vertex-number.visited-cell-count" },
    },
  },
  {
    id: "clue-loop-vertex-number-edge-count",
    name: "格点数字·回路边数",
    kind: "clue", score: null,
    summary: "数字等于格点周围四条邻接边中回路使用的数量。",
    supportedMechanics: ["loop"],
    clue: { kind: "vertex-number", min: 0, max: 4, interpretations: { loop: "数字等于内部格点周围四条相邻格中心连线中回路使用的数量。" }, ruleKeys: { loop: "loop.vertex-number.used-edge-count" } },
  },
  {
    id: "clue-loop-vertex-number-turn-count",
    name: "格点数字·转弯格数",
    kind: "clue", score: null,
    summary: "数字等于格点周围四格中的回路转弯格数。",
    supportedMechanics: ["loop"],
    clue: { kind: "vertex-number", min: 0, max: 4, interpretations: { loop: "数字等于内部格点周围四格中回路转弯的格数。" }, ruleKeys: { loop: "loop.vertex-number.turn-count" } },
  },
  ...pairedLoopDotCards("cell", "clue-loop-cell-dot-straight", "格内点·直行", "回路必须经过点并直行。", "回路必须经过点所在格并直行。", "loop.cell-dot.straight"),
  ...pairedLoopDotCards("cell", "clue-loop-cell-dot-turn", "格内点·转弯", "回路必须经过点并转弯。", "回路必须经过点所在格并转弯。", "loop.cell-dot.turn"),
  {
    id: "clue-loop-cell-dot-equal-arms-white",
    name: "格内白点·等臂",
    kind: "clue", score: null,
    summary: "回路经过白点，从点到前后下一处转弯的两臂等长。",
    supportedMechanics: ["loop"],
    clue: { kind: "white-dot", min: 0, max: 0, interpretations: { loop: "回路必须经过白点；沿回路两个方向从点所在格中心到下一处转弯的长度相等。" }, ruleKeys: { loop: "loop.cell-dot.equal-arm-lengths" } },
  },
  {
    id: "clue-loop-cell-dot-unequal-arms-black",
    name: "格内黑点·异臂",
    kind: "clue", score: null,
    summary: "回路经过黑点，从点到前后下一处转弯的两臂不等长。",
    supportedMechanics: ["loop"],
    clue: { kind: "black-dot", min: 0, max: 0, interpretations: { loop: "回路必须经过黑点；沿回路两个方向从点所在格中心到下一处转弯的长度不相等。" }, ruleKeys: { loop: "loop.cell-dot.unequal-arm-lengths" } },
  },
  ...pairedLoopDotCards("cell", "clue-loop-cell-dot-arm-difference-one", "格内点·臂差一", "回路经过点，前后两臂长度相差 1。", "回路必须经过点；沿回路两个方向从点所在格中心到下一处转弯的长度绝对差为 1。", "loop.cell-dot.arm-length-difference-one"),
  {
    id: "clue-loop-cell-dot-masyu-white",
    name: "格内白点·Masyu",
    kind: "clue", score: null,
    summary: "回路在白点直行，前后至少一格转弯。",
    supportedMechanics: ["loop"],
    clue: { kind: "white-dot", min: 0, max: 0, interpretations: { loop: "回路在白点直行，沿回路相邻的前后两格中至少一格转弯。" }, ruleKeys: { loop: "loop.cell-dot.masyu-white" } },
  },
  {
    id: "clue-loop-cell-dot-masyu-black",
    name: "格内黑点·Masyu",
    kind: "clue", score: null,
    summary: "回路在黑点转弯，前后两格均直行。",
    supportedMechanics: ["loop"],
    clue: { kind: "black-dot", min: 0, max: 0, interpretations: { loop: "回路在黑点转弯，沿回路相邻的前后两格都必须直行。" }, ruleKeys: { loop: "loop.cell-dot.masyu-black" } },
  },
  {
    id: "clue-loop-cell-dot-pearl-black",
    name: "格内黑点·Pearl",
    kind: "clue", score: null,
    summary: "回路经过黑点，前后两格均转弯。",
    supportedMechanics: ["loop"],
    clue: { kind: "black-dot", min: 0, max: 0, interpretations: { loop: "回路经过黑点，沿回路相邻的前后两格都必须转弯。" }, ruleKeys: { loop: "loop.cell-dot.pearl-black" } },
  },
  {
    id: "clue-loop-cell-dot-pearl-white",
    name: "格内白点·Pearl",
    kind: "clue", score: null,
    summary: "回路经过白点，前后两格均直行。",
    supportedMechanics: ["loop"],
    clue: { kind: "white-dot", min: 0, max: 0, interpretations: { loop: "回路经过白点，沿回路相邻的前后两格都必须直行。" }, ruleKeys: { loop: "loop.cell-dot.pearl-white" } },
  },
  {
    id: "clue-loop-edge-dot-through-white",
    name: "边上白点·穿过",
    kind: "clue", score: null,
    summary: "回路必须穿过白点所在边线。",
    supportedMechanics: ["loop"],
    clue: { kind: "edge-white-dot", min: 0, max: 0, interpretations: { loop: "回路必须使用白点所在内部边线连接的两个格子。" }, ruleKeys: { loop: "loop.edge-dot.traversed" } },
  },
  {
    id: "clue-loop-edge-dot-not-through-black",
    name: "边上黑点·不穿过",
    kind: "clue", score: null,
    summary: "回路不能穿过黑点所在边线。",
    supportedMechanics: ["loop"],
    clue: { kind: "edge-black-dot", min: 0, max: 0, interpretations: { loop: "回路不能使用黑点所在内部边线。" }, ruleKeys: { loop: "loop.edge-dot.not-traversed" } },
  },
  ...pairedLoopDotCards("edge", "clue-loop-edge-dot-midpoint", "边上点·线段中点", "回路穿过点，点是所在直线段的中点。", "回路必须穿过点所在内部边线；点到所在最大直线回路段两端的距离相等。", "loop.edge-dot.segment-midpoint"),
  {
    id: "clue-loop-edge-dot-split-difference-one-white",
    name: "边上白点·两端差一",
    kind: "clue", score: null,
    summary: "回路穿过白点，点两侧直到转弯的经过格数相差 1。",
    supportedMechanics: ["loop"],
    clue: { kind: "edge-white-dot", min: 0, max: 0, interpretations: { loop: "回路必须穿过白点所在边线；沿直线段向两端直到转弯格（包含两端相邻格）所经过的格数绝对差为 1。" }, ruleKeys: { loop: "loop.edge-dot.split-cell-count-difference-one" } },
  },
  {
    id: "clue-loop-edge-dot-split-ratio-two-black",
    name: "边上黑点·两端二倍",
    kind: "clue", score: null,
    summary: "回路穿过黑点，点两侧直到转弯的经过格数一边为另一边两倍。",
    supportedMechanics: ["loop"],
    clue: { kind: "edge-black-dot", min: 0, max: 0, interpretations: { loop: "回路必须穿过黑点所在边线；沿直线段向两端直到转弯格（包含两端相邻格）所经过的格数一边恰为另一边的两倍。" }, ruleKeys: { loop: "loop.edge-dot.split-cell-count-ratio-two" } },
  },
  ...pairedLoopDotCards("edge", "clue-loop-edge-dot-same-cell-type", "边上点·同形态", "两侧格均被经过，且同为转弯或直行。", "点两侧格都必须被回路经过，且同为转弯或同为直行。", "loop.edge-dot.same-cell-orientation"),
  ...pairedLoopDotCards("edge", "clue-loop-edge-dot-opposite-cell-type", "边上点·异形态", "两侧格均被经过，且一格转弯一格直行。", "点两侧格都必须被回路经过，且一格转弯、一格直行。", "loop.edge-dot.opposite-cell-orientation"),
  {
    id: "clue-loop-vertex-dot-outside-black",
    name: "格点黑点·回路外",
    kind: "clue", score: null,
    summary: "黑点必须位于回路外部。",
    supportedMechanics: ["loop"],
    clue: { kind: "vertex-black-dot", min: 0, max: 0, interpretations: { loop: "内部格点黑点必须位于回路外。" }, ruleKeys: { loop: "loop.vertex-dot.outside" } },
  },
  {
    id: "clue-loop-vertex-dot-inside-white",
    name: "格点白点·回路内",
    kind: "clue", score: null,
    summary: "白点必须位于回路内部。",
    supportedMechanics: ["loop"],
    clue: { kind: "vertex-white-dot", min: 0, max: 0, interpretations: { loop: "内部格点白点必须位于回路内。" }, ruleKeys: { loop: "loop.vertex-dot.inside" } },
  },
  {
    id: "clue-loop-cell-dot-visited-white",
    name: "格内白点·必须经过",
    kind: "clue",
    score: null,
    summary: "回路必须经过白点所在格。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "white-dot", min: 0, max: 0,
      interpretations: { loop: "回路必须经过白点所在格。" },
      ruleKeys: { loop: "loop.cell-dot.visited" },
    },
  },
  {
    id: "clue-loop-cell-dot-unvisited-black",
    name: "格内黑点·必须避开",
    kind: "clue",
    score: null,
    summary: "回路不能经过黑点所在格。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "black-dot", min: 0, max: 0,
      interpretations: { loop: "回路必须不经过黑点所在格。" },
      ruleKeys: { loop: "loop.cell-dot.unvisited" },
    },
  },
  ...pairedLoopDotCards(
    "cell",
    "clue-loop-cell-dot-unvisited-center-symmetry",
    "格内点·未经过组中心对称",
    "点所在格不走回路，其未经过格连通组以点为中心中心对称。",
    "点所在格必须不被回路经过；其所在未经过格正交连通组以该点为对称中心。",
    "loop.cell-dot.unvisited-component-center-symmetric",
  ),
  ...pairedLoopDotCards(
    "cell",
    "clue-loop-cell-dot-unvisited-axis-symmetry",
    "格内点·未经过组轴对称",
    "点所在格不走回路，其未经过格连通组轴对称且点在轴上。",
    "点所在格必须不被回路经过；其所在未经过格正交连通组关于穿过点的某条网格轴对称。",
    "loop.cell-dot.unvisited-component-axis-symmetric",
  ),
  {
    id: "clue-loop-edge-dot-one-visited-black",
    name: "边上黑点·恰一格经过",
    kind: "clue",
    score: null,
    summary: "黑点两侧的两个格子中恰好一格被回路经过。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "edge-black-dot", min: 0, max: 0,
      interpretations: { loop: "边上黑点两侧的两个格子中必须恰好一格被回路经过。" },
      ruleKeys: { loop: "loop.edge-dot.exactly-one-cell-visited" },
    },
  },
  {
    id: "clue-loop-vertex-dot-more-visited-white",
    name: "格点白点·经过格更多",
    kind: "clue",
    score: null,
    summary: "白点周围四格中经过格多于未经过格。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "vertex-white-dot", min: 0, max: 0,
      interpretations: { loop: "内部格点周围四格中被回路经过的格子必须更多。" },
      ruleKeys: { loop: "loop.vertex-dot.more-visited" },
    },
  },
  {
    id: "clue-loop-vertex-dot-more-unvisited-black",
    name: "格点黑点·未经过格更多",
    kind: "clue",
    score: null,
    summary: "黑点周围四格中未经过格多于经过格。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "vertex-black-dot", min: 0, max: 0,
      interpretations: { loop: "内部格点周围四格中未被回路经过的格子必须更多。" },
      ruleKeys: { loop: "loop.vertex-dot.more-unvisited" },
    },
  },
  {
    id: "clue-loop-exterior-number-visited-cells",
    name: "外提示·经过格数",
    kind: "clue",
    score: null,
    summary: "数字等于对应整行或整列中回路经过的格数。",
    supportedMechanics: ["loop"],
    clue: {
      kind: "exterior-number", min: 0, max: 20,
      interpretations: { loop: "数字等于对应整行或整列中被回路经过的格数；删除格不截断观察。" },
      ruleKeys: { loop: "loop.exterior-number.visited-cell-count" },
    },
  },
  {
    id: "clue-loop-exterior-number-segment-count",
    name: "外提示·平行段数",
    kind: "clue", score: null,
    summary: "数字等于该行或列中与观察方向平行的直线回路段数。",
    supportedMechanics: ["loop"],
    clue: { kind: "exterior-number", min: 0, max: 20, interpretations: { loop: "数字等于整行或整列中与观察方向平行的最大直线回路段数量；垂直穿过不计。" }, ruleKeys: { loop: "loop.exterior-number.parallel-segment-count" } },
  },
  {
    id: "clue-loop-exterior-number-longest-segment",
    name: "外提示·最长平行段",
    kind: "clue", score: null,
    summary: "数字等于该行或列中最长平行直线回路段的长度。",
    supportedMechanics: ["loop"],
    clue: { kind: "exterior-number", min: 1, max: 20, interpretations: { loop: "数字等于整行或整列中与观察方向平行的最大直线回路段的最长边长。" }, ruleKeys: { loop: "loop.exterior-number.longest-parallel-segment" } },
  },
  {
    id: "clue-loop-exterior-number-shortest-segment",
    name: "外提示·最短平行段",
    kind: "clue", score: null,
    summary: "数字等于该行或列中最短平行直线回路段的长度。",
    supportedMechanics: ["loop"],
    clue: { kind: "exterior-number", min: 1, max: 20, interpretations: { loop: "数字等于整行或整列中与观察方向平行的最大直线回路段的最短边长。" }, ruleKeys: { loop: "loop.exterior-number.shortest-parallel-segment" } },
  },
  {
    id: "clue-shade-cell-number-orthogonal",
    name: "格内数字·邻黑",
    kind: "clue",
    score: null,
    summary: "数字格留白，数字等于正交相邻格中的涂黑格数量。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "cell-number",
      min: 0,
      max: 4,
      interpretations: { shade: "自身留白，数字等于周围四格中的涂黑格数量。" },
      ruleKeys: { shade: "shade.cell-number.orthogonal-black" },
    },
  },
  {
    id: "clue-shade-cell-number-plus-self",
    name: "格内数字·含自身",
    kind: "clue",
    score: null,
    summary: "数字等于自身和正交相邻格中的涂黑格数量。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "cell-number",
      min: 0,
      max: 5,
      interpretations: { shade: "数字等于自身及周围四格中的涂黑格数量。" },
      ruleKeys: { shade: "shade.cell-number.orthogonal-plus-self-black" },
    },
  },
  {
    id: "clue-shade-cell-number-surrounding-eight",
    name: "格内数字·八邻",
    kind: "clue",
    score: null,
    summary: "数字格留白，数字等于周围八格中的涂黑格数量。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "cell-number",
      min: 0,
      max: 8,
      interpretations: { shade: "自身留白，数字等于周围八格中的涂黑格数量。" },
      ruleKeys: { shade: "shade.cell-number.surrounding-eight-black" },
    },
  },
  {
    id: "clue-shade-cell-number-canal-view",
    name: "格内数字·运河视野",
    kind: "clue",
    score: null,
    summary: "数字格留白，统计四个方向上紧邻数字格的连续黑格总数。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "cell-number",
      min: 0,
      max: 20,
      interpretations: { shade: "自身留白；数字等于四个方向上、直到首个白格或边界为止的连续黑格总数。" },
      ruleKeys: { shade: "shade.cell-number.canal-view" },
    },
  },
  {
    id: "clue-shade-cell-number-kurodoko",
    name: "格内数字·Kurodoko",
    kind: "clue",
    score: null,
    summary: "数字格留白，数字等于包含自身的四向可见白格总数。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "cell-number",
      min: 1,
      max: 20,
      interpretations: { shade: "自身留白；数字等于包含自身的四向可见白格总数，黑格、缺口与边界截断视线。" },
      ruleKeys: { shade: "shade.cell-number.kurodoko" },
    },
  },
  {
    id: "clue-shade-cell-number-white-component",
    name: "格内数字·白区大小",
    kind: "clue",
    score: null,
    summary: "数字格留白，数字等于其所在白格连通组的大小。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "cell-number",
      min: 1,
      max: 99,
      interpretations: { shade: "自身留白；数字等于其所在白格正交连通组的大小。" },
      ruleKeys: { shade: "shade.cell-number.white-component-size" },
    },
  },
  {
    id: "clue-shade-cell-number-kurotto",
    name: "格内数字·Kurotto",
    kind: "clue",
    score: null,
    summary: "数字格留白，数字等于其四周接触到的不同黑格连通组大小之和。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "cell-number",
      min: 0,
      max: 99,
      interpretations: { shade: "自身留白；将正交或对角接触到的不同黑格连通组各计一次，数字等于它们的大小之和。" },
      ruleKeys: { shade: "shade.cell-number.kurotto" },
    },
  },
  {
    id: "clue-shade-edge-number-count",
    name: "边线数字·黑格数",
    kind: "clue",
    score: null,
    summary: "数字等于边线两侧格子中的涂黑格数量。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "edge-number",
      min: 0,
      max: 2,
      interpretations: { shade: "数字等于该内部边线覆盖的两个格子中的涂黑格数量。" },
      ruleKeys: { shade: "shade.edge-number.black-count" },
    },
  },
  {
    id: "clue-shade-edge-number-component-sum",
    name: "边线数字·组大小和",
    kind: "clue",
    score: null,
    summary: "边线两侧一黑一白，数字等于两个同色连通组的大小之和。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "edge-number",
      min: 2,
      max: 99,
      interpretations: { shade: "两侧必须一黑一白；数字等于黑格与白格各自所在正交连通组大小之和。" },
      ruleKeys: { shade: "shade.edge-number.component-size-sum" },
    },
  },
  {
    id: "clue-shade-edge-number-component-difference",
    name: "边线数字·组大小差",
    kind: "clue",
    score: null,
    summary: "边线两侧一黑一白，数字等于两个同色连通组大小的绝对差。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "edge-number",
      min: 0,
      max: 99,
      interpretations: { shade: "两侧必须一黑一白；数字等于黑格与白格各自所在正交连通组大小的绝对差。" },
      ruleKeys: { shade: "shade.edge-number.component-size-difference" },
    },
  },
  {
    id: "clue-shade-vertex-number-count",
    name: "格点数字·黑格数",
    kind: "clue",
    score: null,
    summary: "数字等于内部格点周围四格中的涂黑格数量。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "vertex-number",
      min: 0,
      max: 4,
      interpretations: { shade: "数字等于该内部格点周围四格中的涂黑格数量。" },
      ruleKeys: { shade: "shade.vertex-number.black-count" },
    },
  },
  {
    id: "clue-shade-vertex-number-land-measurement",
    name: "格点数字·Land Measurement",
    kind: "clue",
    score: null,
    summary: "周围四格形成棋盘格，数字为两个黑格间最短黑格路径包含的格数。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "vertex-number",
      min: 3,
      max: 99,
      interpretations: { shade: "周围四格必须为棋盘格；两个黑格须由黑格正交连通，数字为最短路径包含起终点的格数。" },
      ruleKeys: { shade: "shade.vertex-number.land-measurement" },
    },
  },
  {
    id: "clue-shade-exterior-number-count",
    name: "外提示·黑格数",
    kind: "clue",
    score: null,
    summary: "数字等于所观察整行或整列中的涂黑格数量。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "exterior-number",
      min: 0,
      max: 20,
      interpretations: { shade: "数字等于该方向所观察整行或整列中的涂黑格数量；删除格子不会截断观察。" },
      ruleKeys: { shade: "shade.exterior-number.black-count" },
    },
  },
  {
    id: "clue-shade-exterior-number-segments",
    name: "外提示·黑格段数",
    kind: "clue",
    score: null,
    summary: "数字等于所观察行列中的黑格段数量，删除格会切断黑格段。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "exterior-number",
      min: 0,
      max: 20,
      interpretations: { shade: "数字等于整行或整列中的黑格段数量；白格和删除格都会分隔黑格段。" },
      ruleKeys: { shade: "shade.exterior-number.black-segment-count" },
    },
  },
  {
    id: "clue-shade-exterior-number-longest-segment",
    name: "外提示·最长黑段",
    kind: "clue",
    score: null,
    summary: "数字等于所观察行列中最长黑格段的长度。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "exterior-number",
      min: 1,
      max: 20,
      interpretations: { shade: "数字等于整行或整列中最长黑格段的长度；删除格会切断黑格段。" },
      ruleKeys: { shade: "shade.exterior-number.longest-black-segment" },
    },
  },
  {
    id: "clue-shade-exterior-number-first-segment",
    name: "外提示·首个黑段",
    kind: "clue",
    score: null,
    summary: "数字等于从提示方向看到的第一段黑格长度。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "exterior-number",
      min: 1,
      max: 20,
      interpretations: { shade: "沿提示方向观察完整行列，数字等于遇到的第一段黑格长度；删除格切断段但不截断观察。" },
      ruleKeys: { shade: "shade.exterior-number.first-black-segment" },
    },
  },
  {
    id: "clue-white-dot",
    name: "白点",
    kind: "clue",
    score: null,
    summary: "轻量的位置线索，解释取决于主要玩法。",
    supportedMechanics: ["loop", "shade", "region"],
    clue: {
      kind: "white-dot",
      min: 0,
      max: 0,
      interpretations: {
        loop: "回路在白点处直行。",
        shade: "白点所在格不能涂黑。",
        region: "白点两侧属于同一区域。",
      },
      ruleKeys: {
        loop: "loop.white-dot.straight",
        shade: "shade.white-dot.unshaded",
      },
    },
  },
  {
    id: "clue-black-dot",
    name: "黑点",
    kind: "clue",
    score: null,
    summary: "强约束的位置线索，解释取决于主要玩法。",
    supportedMechanics: ["loop", "shade", "region"],
    clue: {
      kind: "black-dot",
      min: 0,
      max: 0,
      interpretations: {
        loop: "回路在黑点处转弯。",
        shade: "黑点所在格必须涂黑。",
        region: "黑点两侧属于不同区域。",
      },
      ruleKeys: {
        loop: "loop.black-dot.turn",
        shade: "shade.black-dot.shaded",
      },
    },
  },
  ...pairedCellDotCards(
    "clue-shade-cell-dot-center-symmetry",
    "点所在组中心对称",
    "点所在格的同色连通组必须以点为中心中心对称。",
    "点所在格的同色正交连通组必须以该点为对称中心。",
    "shade.cell-dot.component-center-symmetric",
  ),
  ...pairedCellDotCards(
    "clue-shade-cell-dot-axis-symmetry",
    "点所在组轴对称",
    "点所在格的同色连通组必须轴对称，且点位于对称轴上。",
    "点所在格的同色正交连通组必须关于穿过该点的水平、竖直或对角轴之一对称。",
    "shade.cell-dot.component-axis-symmetric",
  ),
  ...pairedCellDotCards(
    "clue-shade-cell-dot-one-white-neighbor",
    "邻格恰一白",
    "点的正交邻格中必须恰好有一个白格。",
    "点周围至多四个正交邻格中必须恰好有一个白格。",
    "shade.cell-dot.exactly-one-white-neighbor",
  ),
  {
    id: "clue-shade-edge-dot-both-white",
    name: "边上白点·两侧白",
    kind: "clue",
    score: null,
    summary: "白点两侧的两个格子都必须留白。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "edge-white-dot",
      min: 0,
      max: 0,
      interpretations: { shade: "边上白点两侧的两个格子都不能涂黑。" },
      ruleKeys: { shade: "shade.edge-dot.both-white" },
    },
  },
  ...pairedAnchoredDotCards(
    "edge",
    "clue-shade-edge-dot-one-black",
    "边上点·一黑一白",
    "点两侧恰好一格涂黑。",
    "边上点两侧必须恰好一黑一白。",
    "shade.edge-dot.exactly-one-black",
  ),
  {
    id: "clue-shade-edge-dot-both-black",
    name: "边上黑点·两侧黑",
    kind: "clue",
    score: null,
    summary: "黑点两侧的两个格子都必须涂黑。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "edge-black-dot",
      min: 0,
      max: 0,
      interpretations: { shade: "边上黑点两侧的两个格子都必须涂黑。" },
      ruleKeys: { shade: "shade.edge-dot.both-black" },
    },
  },
  ...pairedAnchoredDotCards(
    "edge",
    "clue-shade-edge-dot-congruent-components",
    "边上点·同色组全等",
    "两侧一黑一白，两个格子的同色连通组经旋转和平移后全等。",
    "两侧必须一黑一白；各自所在同色连通组允许旋转和平移后全等，不允许翻转。",
    "shade.edge-dot.opposite-congruent-components",
  ),
  ...pairedAnchoredDotCards(
    "edge",
    "clue-shade-edge-dot-mirrored-components",
    "边上点·同色组镜像",
    "两侧一黑一白，两个同色连通组关于点所在边线互为镜像。",
    "两侧必须一黑一白；各自所在同色连通组必须关于点所在边线恰好互为镜像。",
    "shade.edge-dot.opposite-mirrored-components",
  ),
  {
    id: "clue-shade-vertex-dot-more-black",
    name: "格点黑点·黑多",
    kind: "clue",
    score: null,
    summary: "黑点周围四格中，黑格必须多于白格。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "vertex-black-dot",
      min: 0,
      max: 0,
      interpretations: { shade: "内部格点周围四格中黑格数量必须多于白格数量。" },
      ruleKeys: { shade: "shade.vertex-dot.more-black-than-white" },
    },
  },
  {
    id: "clue-shade-vertex-dot-more-white",
    name: "格点白点·白多",
    kind: "clue",
    score: null,
    summary: "白点周围四格中，白格必须多于黑格。",
    supportedMechanics: ["shade"],
    clue: {
      kind: "vertex-white-dot",
      min: 0,
      max: 0,
      interpretations: { shade: "内部格点周围四格中白格数量必须多于黑格数量。" },
      ruleKeys: { shade: "shade.vertex-dot.more-white-than-black" },
    },
  },
  ...pairedAnchoredDotCards(
    "vertex",
    "clue-shade-vertex-dot-checkerboard",
    "格点点·棋盘格",
    "周围四格必须恰好两黑两白并形成棋盘格。",
    "内部格点周围四格必须恰好两黑两白，且同色格位于对角位置。",
    "shade.vertex-dot.checkerboard",
  ),
  {
    id: "tool-remove-clue",
    name: "橡皮擦",
    kind: "tool",
    score: null,
    summary: "移除盘面上的一个线索。",
    supportedMechanics: [],
    toolEffect: "remove-clue",
  },
  {
    id: "tool-remove-cell",
    name: "裁纸刀",
    kind: "tool",
    score: null,
    summary: "移除一个格子及格内线索，盘面可以变为不规则形状。",
    supportedMechanics: [],
    toolEffect: "remove-cell",
  },
  {
    id: "tool-remove-clue-card",
    name: "改写注释",
    kind: "tool",
    score: null,
    summary: "移除盘面上的一张线索牌。",
    supportedMechanics: [],
    toolEffect: "remove-clue-card",
  },
  {
    id: "tool-remove-global-card",
    name: "撕掉规则",
    kind: "tool",
    score: null,
    summary: "移除盘面上的一张全局规则牌。",
    supportedMechanics: [],
    toolEffect: "remove-global-card",
  },
];

export const CARD_BY_ID = new Map(CARD_DEFINITIONS.map((card) => [card.id, card]));

export function cardsOfKind(kind: CardKind) {
  return CARD_DEFINITIONS.filter((card) => card.kind === kind && !card.id.startsWith("rule-koburin"));
}

export function getCard(definitionId: string) {
  const card = CARD_BY_ID.get(definitionId);
  if (!card) throw new Error(`Unknown card definition: ${definitionId}`);
  return card;
}

export function cardEntries(card: Pick<CardInstance, "definitionId" | "entryDefinitionIds">) {
  return (card.entryDefinitionIds?.length ? card.entryDefinitionIds : [card.definitionId]).flatMap((definitionId) => {
    const definition = getCard(definitionId);
    if (!definition.clue) return [definition];
    const mechanics = Object.keys(definition.clue.interpretations) as BoardMechanic[];
    if (mechanics.length <= 1) return [definition];
    return mechanics.map((mechanic) => ({
      ...definition,
      id: `${definition.id}@${mechanic}`,
      supportedMechanics: [mechanic],
      clue: {
        ...definition.clue!,
        interpretations: { [mechanic]: definition.clue!.interpretations[mechanic] },
        ruleKeys: definition.clue!.ruleKeys?.[mechanic] ? { [mechanic]: definition.clue!.ruleKeys[mechanic] } : undefined,
      },
    }));
  });
}

export function clueEntryForMechanic(
  card: Pick<CardInstance, "definitionId" | "entryDefinitionIds">,
  mechanic: BoardMechanic | null,
) {
  const entries = cardEntries(card);
  if (!mechanic) return entries.find((entry) => entry.clue) ?? entries[0];
  return entries.find((entry) => entry.clue?.interpretations[mechanic]);
}
