import { RULE_COMPILER_REGISTRY } from "./solver";
import { RULESET } from "./ruleset";
import type { BoardMechanic } from "./types";

export interface SolverCoverageEntry {
  ordinal: number;
  ruleKey: string;
  tested: boolean;
}

// Authoritative bridge from ruleset.txt entries to executable constraint compilers.
// Add an entry only after the rule has both an implementation and a regression test.
export const SOLVER_COVERAGE: SolverCoverageEntry[] = [
  { ordinal: 1, ruleKey: "shade.connected", tested: true },
  { ordinal: 2, ruleKey: "shade.white-connected", tested: true },
  { ordinal: 3, ruleKey: "shade.no-black-2x2", tested: true },
  { ordinal: 4, ruleKey: "shade.no-white-2x2", tested: true },
  { ordinal: 5, ruleKey: "shade.no-monochrome-run-3", tested: true },
  { ordinal: 6, ruleKey: "shade.no-monochrome-run-4", tested: true },
  { ordinal: 7, ruleKey: "shade.equal-row-column-counts", tested: true },
  { ordinal: 8, ruleKey: "shade.black-cells-do-not-touch", tested: true },
  { ordinal: 9, ruleKey: "shade.single-snake", tested: true },
  { ordinal: 10, ruleKey: "number.latin-1-to-n-full", tested: true },
  { ordinal: 11, ruleKey: "number.latin-1-to-n-minus-one", tested: true },
  { ordinal: 12, ruleKey: "number.latin-1-to-n-minus-two", tested: true },
  { ordinal: 13, ruleKey: "number.digit-cells-connected-no-equal-adjacency", tested: true },
  { ordinal: 14, ruleKey: "loop.unvisited-not-adjacent", tested: true },
  { ordinal: 15, ruleKey: "loop.visit-all-unclued-cells", tested: true },
  { ordinal: 16, ruleKey: "region.rectangles", tested: true },
  { ordinal: 17, ruleKey: "region.center-symmetric", tested: true },
  { ordinal: 18, ruleKey: "region.exactly-one-cell-clue", tested: true },
  { ordinal: 19, ruleKey: "region.all-shapes-distinct", tested: true },
  { ordinal: 20, ruleKey: "shade.cell-number.orthogonal-black", tested: true },
  { ordinal: 21, ruleKey: "shade.cell-number.orthogonal-plus-self-black", tested: true },
  { ordinal: 22, ruleKey: "shade.cell-number.surrounding-eight-black", tested: true },
  { ordinal: 23, ruleKey: "shade.cell-number.neighborhood-nine", tested: true },
  { ordinal: 24, ruleKey: "shade.cell-number.kurodoko", tested: true },
  { ordinal: 25, ruleKey: "shade.cell-number.canal-view", tested: true },
  { ordinal: 26, ruleKey: "shade.cell-number.white-component-size", tested: true },
  { ordinal: 27, ruleKey: "shade.cell-number.kurotto", tested: true },
  { ordinal: 28, ruleKey: "number.cell-number.fixed", tested: true },
  { ordinal: 29, ruleKey: "loop.cell-number.eight-visited", tested: true },
  { ordinal: 30, ruleKey: "loop.cell-number.eight-turns", tested: true },
  { ordinal: 31, ruleKey: "loop.cell-number.eight-unvisited", tested: true },
  { ordinal: 32, ruleKey: "loop.cell-number.four-turns", tested: true },
  { ordinal: 33, ruleKey: "loop.cell-number.four-visited", tested: true },
  { ordinal: 34, ruleKey: "loop.cell-number.orthogonal-unvisited", tested: true },
  { ordinal: 35, ruleKey: "loop.cell-number.outward-segment-length-sum", tested: true },
  { ordinal: 36, ruleKey: "loop.cell-number.arm-length-sum", tested: true },
  { ordinal: 37, ruleKey: "loop.cell-number.inside-vertex-count", tested: true },
  { ordinal: 38, ruleKey: "region.cell-number.area", tested: true },
  { ordinal: 39, ruleKey: "region.cell-number.adjacent-boundary-count", tested: true },
  { ordinal: 40, ruleKey: "region.cell-number.neighboring-region-count", tested: true },
  { ordinal: 41, ruleKey: "region.cell-number.perimeter", tested: true },
  { ordinal: 42, ruleKey: "shade.edge-number.black-count", tested: true },
  { ordinal: 43, ruleKey: "shade.edge-number.component-size-sum", tested: true },
  { ordinal: 44, ruleKey: "shade.edge-number.component-size-difference", tested: true },
  { ordinal: 45, ruleKey: "number.edge-number.sum", tested: true },
  { ordinal: 46, ruleKey: "number.edge-number.difference", tested: true },
  { ordinal: 47, ruleKey: "number.edge-number.product", tested: true },
  { ordinal: 48, ruleKey: "number.edge-number.contains", tested: true },
  { ordinal: 49, ruleKey: "number.edge-number.arithmetic", tested: true },
  { ordinal: 50, ruleKey: "loop.edge-number.segment-length", tested: true },
  { ordinal: 51, ruleKey: "loop.edge-number.outward-segment-length-sum", tested: true },
  { ordinal: 52, ruleKey: "loop.edge-number.visited-cell-count", tested: true },
  { ordinal: 53, ruleKey: "region.edge-number.area-sum", tested: true },
  { ordinal: 54, ruleKey: "region.edge-number.area-difference", tested: true },
  { ordinal: 55, ruleKey: "region.edge-number.boundary-length", tested: true },
  { ordinal: 56, ruleKey: "shade.vertex-number.black-count", tested: true },
  { ordinal: 57, ruleKey: "shade.vertex-number.land-measurement", tested: true },
  { ordinal: 58, ruleKey: "number.vertex-number.sum", tested: true },
  { ordinal: 59, ruleKey: "number.vertex-number.contains", tested: true },
  { ordinal: 60, ruleKey: "number.vertex-number.diagonal-sums", tested: true },
  { ordinal: 61, ruleKey: "number.vertex-number.diagonal-differences", tested: true },
  { ordinal: 62, ruleKey: "number.vertex-number.diagonal-arithmetic", tested: true },
  { ordinal: 63, ruleKey: "loop.vertex-number.used-edge-count", tested: true },
  { ordinal: 64, ruleKey: "loop.vertex-number.visited-cell-count", tested: true },
  { ordinal: 65, ruleKey: "loop.vertex-number.turn-count", tested: true },
  { ordinal: 66, ruleKey: "region.vertex-number.distinct-region-count", tested: true },
  { ordinal: 67, ruleKey: "region.vertex-number.region-area-sum", tested: true },
  { ordinal: 68, ruleKey: "region.vertex-number.distinct-shape-count", tested: true },
  { ordinal: 69, ruleKey: "shade.black-dot.shaded", tested: true },
  { ordinal: 70, ruleKey: "shade.white-dot.unshaded", tested: true },
  { ordinal: 71, ruleKey: "shade.cell-dot.component-center-symmetric", tested: true },
  { ordinal: 72, ruleKey: "shade.cell-dot.component-axis-symmetric", tested: true },
  { ordinal: 73, ruleKey: "shade.cell-dot.exactly-one-white-neighbor", tested: true },
  { ordinal: 74, ruleKey: "number.cell-dot.empty", tested: true },
  { ordinal: 75, ruleKey: "number.cell-dot.filled", tested: true },
  { ordinal: 76, ruleKey: "number.cell-dot.odd", tested: true },
  { ordinal: 77, ruleKey: "number.cell-dot.even", tested: true },
  { ordinal: 78, ruleKey: "number.cell-dot.same-color-equal", tested: true },
  { ordinal: 79, ruleKey: "number.cell-dot.greater-than-neighbors", tested: true },
  { ordinal: 80, ruleKey: "number.cell-dot.less-than-neighbors", tested: true },
  { ordinal: 81, ruleKey: "loop.cell-dot.visited", tested: true },
  { ordinal: 82, ruleKey: "loop.cell-dot.unvisited", tested: true },
  { ordinal: 83, ruleKey: "loop.cell-dot.unvisited-component-center-symmetric", tested: true },
  { ordinal: 84, ruleKey: "loop.cell-dot.unvisited-component-axis-symmetric", tested: true },
  { ordinal: 85, ruleKey: "loop.cell-dot.equal-arm-lengths", tested: true },
  { ordinal: 86, ruleKey: "loop.cell-dot.unequal-arm-lengths", tested: true },
  { ordinal: 87, ruleKey: "loop.cell-dot.arm-length-difference-one", tested: true },
  { ordinal: 88, ruleKey: "loop.cell-dot.straight", tested: true },
  { ordinal: 89, ruleKey: "loop.cell-dot.turn", tested: true },
  { ordinal: 90, ruleKey: "loop.cell-dot.masyu-white", tested: true },
  { ordinal: 91, ruleKey: "loop.cell-dot.masyu-black", tested: true },
  { ordinal: 92, ruleKey: "loop.cell-dot.pearl-black", tested: true },
  { ordinal: 93, ruleKey: "loop.cell-dot.pearl-white", tested: true },
  { ordinal: 94, ruleKey: "region.cell-dot.orthogonal-neighborhood-same-region", tested: true },
  { ordinal: 95, ruleKey: "region.cell-dot.center-symmetric-about-point", tested: true },
  { ordinal: 96, ruleKey: "region.cell-dot.axis-symmetric-through-point", tested: true },
  { ordinal: 97, ruleKey: "region.cell-dot.same-color-rotationally-congruent", tested: true },
  { ordinal: 98, ruleKey: "region.cell-dot.same-color-translation-congruent", tested: true },
  { ordinal: 99, ruleKey: "shade.edge-dot.both-white", tested: true },
  { ordinal: 100, ruleKey: "shade.edge-dot.exactly-one-black", tested: true },
  { ordinal: 101, ruleKey: "shade.edge-dot.both-black", tested: true },
  { ordinal: 102, ruleKey: "shade.edge-dot.opposite-congruent-components", tested: true },
  { ordinal: 103, ruleKey: "shade.edge-dot.opposite-mirrored-components", tested: true },
  { ordinal: 104, ruleKey: "number.edge-dot.both-filled", tested: true },
  { ordinal: 105, ruleKey: "number.edge-dot.exactly-one-filled", tested: true },
  { ordinal: 106, ruleKey: "number.edge-dot.both-empty", tested: true },
  { ordinal: 107, ruleKey: "number.edge-dot.difference-one", tested: true },
  { ordinal: 108, ruleKey: "number.edge-dot.ratio-two", tested: true },
  { ordinal: 109, ruleKey: "number.edge-dot.sum-five", tested: true },
  { ordinal: 110, ruleKey: "number.edge-dot.sum-ten", tested: true },
  { ordinal: 111, ruleKey: "number.edge-dot.same-color-equal-sums", tested: true },
  { ordinal: 112, ruleKey: "loop.edge-dot.traversed", tested: true },
  { ordinal: 113, ruleKey: "loop.edge-dot.not-traversed", tested: true },
  { ordinal: 114, ruleKey: "loop.edge-dot.segment-midpoint", tested: true },
  { ordinal: 115, ruleKey: "loop.edge-dot.split-cell-count-difference-one", tested: true },
  { ordinal: 116, ruleKey: "loop.edge-dot.split-cell-count-ratio-two", tested: true },
  { ordinal: 117, ruleKey: "loop.edge-dot.exactly-one-cell-visited", tested: true },
  { ordinal: 118, ruleKey: "loop.edge-dot.same-cell-orientation", tested: true },
  { ordinal: 119, ruleKey: "loop.edge-dot.opposite-cell-orientation", tested: true },
  { ordinal: 120, ruleKey: "region.edge-dot.boundary", tested: true },
  { ordinal: 121, ruleKey: "region.edge-dot.rotationally-congruent-regions", tested: true },
  { ordinal: 122, ruleKey: "region.edge-dot.mirrored-regions", tested: true },
  { ordinal: 123, ruleKey: "region.edge-dot.center-symmetric-about-point", tested: true },
  { ordinal: 124, ruleKey: "region.edge-dot.axis-symmetric-through-point", tested: true },
  { ordinal: 125, ruleKey: "shade.vertex-dot.more-black-than-white", tested: true },
  { ordinal: 126, ruleKey: "shade.vertex-dot.more-white-than-black", tested: true },
  { ordinal: 127, ruleKey: "shade.vertex-dot.checkerboard", tested: true },
  { ordinal: 128, ruleKey: "number.vertex-dot.more-even", tested: true },
  { ordinal: 129, ruleKey: "number.vertex-dot.more-odd", tested: true },
  { ordinal: 130, ruleKey: "number.vertex-dot.more-empty", tested: true },
  { ordinal: 131, ruleKey: "number.vertex-dot.more-filled", tested: true },
  { ordinal: 132, ruleKey: "number.vertex-dot.clockwise-increasing", tested: true },
  { ordinal: 133, ruleKey: "number.vertex-dot.counterclockwise-increasing", tested: true },
  { ordinal: 134, ruleKey: "number.vertex-dot.exactly-one-consecutive-pair", tested: true },
  { ordinal: 135, ruleKey: "number.vertex-dot.at-least-two-consecutive-pairs", tested: true },
  { ordinal: 136, ruleKey: "loop.vertex-dot.outside", tested: true },
  { ordinal: 137, ruleKey: "loop.vertex-dot.inside", tested: true },
  { ordinal: 138, ruleKey: "loop.vertex-dot.more-visited", tested: true },
  { ordinal: 139, ruleKey: "loop.vertex-dot.more-unvisited", tested: true },
  { ordinal: 140, ruleKey: "region.vertex-dot.three-lines", tested: true },
  { ordinal: 141, ruleKey: "region.vertex-dot.four-lines", tested: true },
  { ordinal: 142, ruleKey: "region.vertex-dot.zero-lines", tested: true },
  { ordinal: 143, ruleKey: "region.vertex-dot.center-symmetric-about-point", tested: true },
  { ordinal: 144, ruleKey: "region.vertex-dot.axis-symmetric-through-point", tested: true },
  { ordinal: 145, ruleKey: "shade.exterior-number.black-count", tested: true },
  { ordinal: 146, ruleKey: "shade.exterior-number.black-segment-count", tested: true },
  { ordinal: 147, ruleKey: "shade.exterior-number.longest-black-segment", tested: true },
  { ordinal: 148, ruleKey: "shade.exterior-number.first-black-segment", tested: true },
  { ordinal: 149, ruleKey: "number.exterior-number.first-number", tested: true },
  { ordinal: 150, ruleKey: "number.exterior-number.skyscraper-count", tested: true },
  { ordinal: 151, ruleKey: "number.exterior-number.skyscraper-sum", tested: true },
  { ordinal: 152, ruleKey: "number.exterior-number.first-two-contain", tested: true },
  { ordinal: 153, ruleKey: "loop.exterior-number.visited-cell-count", tested: true },
  { ordinal: 154, ruleKey: "loop.exterior-number.parallel-segment-count", tested: true },
  { ordinal: 155, ruleKey: "loop.exterior-number.longest-parallel-segment", tested: true },
  { ordinal: 156, ruleKey: "loop.exterior-number.shortest-parallel-segment", tested: true },
  { ordinal: 157, ruleKey: "region.exterior-number.distinct-region-count", tested: true },
  { ordinal: 158, ruleKey: "region.exterior-number.longest-run", tested: true },
  { ordinal: 159, ruleKey: "region.exterior-number.shortest-run", tested: true },
];

export function auditSolverCoverage() {
  const registry = new Set(RULE_COMPILER_REGISTRY.map((rule) => rule.key));
  const byOrdinal = new Map(SOLVER_COVERAGE.map((entry) => [entry.ordinal, entry]));
  const invalid = SOLVER_COVERAGE.filter((entry) => !registry.has(entry.ruleKey) || !RULESET[entry.ordinal - 1] || !entry.tested);
  const counts = Object.fromEntries((["shade", "loop", "number", "region"] as BoardMechanic[]).map((mechanic) => {
    const rules = RULESET.filter((rule) => rule.mechanic === mechanic);
    const implemented = rules.filter((rule) => byOrdinal.has(rule.ordinal)).length;
    return [mechanic, { implemented, total: rules.length }];
  })) as Record<BoardMechanic, { implemented: number; total: number }>;
  return {
    implemented: SOLVER_COVERAGE.length,
    total: RULESET.length,
    missingOrdinals: RULESET.filter((rule) => !byOrdinal.has(rule.ordinal)).map((rule) => rule.ordinal),
    invalid,
    counts,
  };
}
